# Generated by Django 4.2.4 on 2023-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('category', models.CharField(blank=True, choices=[['Sport', 'Sport'], ['Culture', 'Culture'], ['Education', 'Education'], ['Hobby', 'Hobby']], max_length=255, null=True, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
