# Generated by Django 4.2.4 on 2023-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_image_alter_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
