# Generated by Django 4.2.4 on 2023-08-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_map_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
    ]
