# Generated by Django 4.2.4 on 2023-08-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFromPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Мероприятие из паблика',
                'verbose_name_plural': 'Мероприятия из пабликов',
            },
        ),
    ]
